name: Build and Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:TreatWarningsAsErrors=true --no-restore

      - name: Run tests with coverage
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAssembly="BluQube.SourceGeneration"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: '**/coverage.cobertura.xml'
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Pack
        run: dotnet pack --configuration Release -p:ContinuousIntegrationBuild=true -p:SymbolPackageFormat=snupkg --output ./artifacts

      - name: Generate SBOM
        run: dotnet CycloneDX src/BluQube/BluQube.csproj --configuration Release --disable-package-restore --output ./artifacts/sbom --output-format Json --exclude-dev --set-name BluQube --set-type Library

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ./artifacts/sbom/*
        
      - name: Push to MyGet
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source https://www.myget.org/F/bluqube/api/v3/index.json \
            --api-key ${{ secrets.MYGET_API_KEY }}

      - name: NuGet login
        if: startsWith(github.ref, 'refs/tags/')
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: roly445

      - name: Push to NuGet.org
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
